from app.models import (  # noqa: F401
    auth,
    intelligence,
    management,
    monitoring,
    scanning,
    sectors,
    tenants,
)

ALL_SCHEMAS = [
    "auth",
    "tenants",
    "scan_scope",
    "red_team",
    "blue_team",
    "soc",
    "incidents",
    "sigma",
    "honeypot",
    "threat_hunting",
    "pipeline",
    "ai_brain",
    "automation",
    "threat_intel",
    "federation",
    "banking",
    "ot_scada",
    "ueba",
    "swift_csp",
    "aml",
    "sector_monitor",
    "grc",
    "analytics",
    "reports",
    "phishing",
    "settings",
]
